Repository ssu-Recipable/BackEnd, pull requests merged in 2024-05, with the labels that each got.

#21 Fix: 인증번호 반환 타입 변경
  src/main/java/capstone/recipable/domain/auth/jwt/dto/CustomUserDetails.java
  src/main/java/capstone/recipable/domain/auth/jwt/service/CustomUserDetailsService.java
  src/main/java/capstone/recipable/domain/register/controller/RegisterController.java
  src/main/java/capstone/recipable/domain/register/dto/request/RegisterRequest.java
  src/main/java/capstone/recipable/domain/register/dto/response/CodeResponse.java
  src/main/java/capstone/recipable/domain/register/service/RegisterService.java
Labels: fix

#22 Fix: 이메일 인증 이슈 수정
  src/main/java/capstone/recipable/domain/register/controller/RegisterController.java
Labels: fix

#24 [Feat]: 유튜브 링크 api
  build.gradle
  src/main/java/capstone/recipable/domain/auth/oauth/service/KakaoService.java
  src/main/java/capstone/recipable/domain/login/controller/LoginController.java
  src/main/java/capstone/recipable/domain/login/dto/request/LoginRequest.java
  src/main/java/capstone/recipable/domain/youtube/controller/YoutubeController.java
  src/main/java/capstone/recipable/domain/youtube/dto/response/YoutubeResponse.java
  src/main/java/capstone/recipable/domain/youtube/service/YoutubeService.java
Labels: feature

#27 [Refactor]: 응답통일 코드
  src/main/java/capstone/recipable/domain/auth/jwt/SecurityContextProvider.java
  src/main/java/capstone/recipable/global/entity/BaseEntity.java
  src/main/java/capstone/recipable/global/error/ApiResponse.java
  src/main/java/capstone/recipable/global/error/ApplicationException.java
  src/main/java/capstone/recipable/global/error/ApplicationExceptionHandler.java
  src/main/java/capstone/recipable/global/error/ErrorCode.java
  src/main/java/capstone/recipable/global/error/ErrorResponse.java
  src/main/java/capstone/recipable/global/error/code/BaseCode.java
  src/main/java/capstone/recipable/global/error/code/BaseErrorCode.java
  src/main/java/capstone/recipable/global/error/dto/ErrorReasonDto.java
  src/main/java/capstone/recipable/global/error/dto/ReasonDto.java
  src/main/java/capstone/recipable/global/error/exception/ExceptionAdvice.java
  src/main/java/capstone/recipable/global/error/exception/GeneralException.java
  src/main/java/capstone/recipable/global/error/exception/InvalidValueException.java
  src/main/java/capstone/recipable/global/error/status/ErrorStatus.java
  src/main/java/capstone/recipable/global/error/status/SuccessStatus.java
  src/main/java/capstone/recipable/global/response/SuccessCode.java
  src/main/java/capstone/recipable/global/response/SuccessResponse.java
Labels: refactor

#30 Feat: 사용자 정보 조회, 수정 api
  src/main/java/capstone/recipable/domain/auth/config/BCryptConfig.java
  src/main/java/capstone/recipable/domain/auth/config/MailConfig.java
  src/main/java/capstone/recipable/domain/auth/controller/LoginController.java
  src/main/java/capstone/recipable/domain/auth/controller/RegisterController.java
  src/main/java/capstone/recipable/domain/auth/dto/request/EmailRequest.java
  src/main/java/capstone/recipable/domain/auth/dto/request/LoginRequest.java
  src/main/java/capstone/recipable/domain/auth/dto/request/RegisterRequest.java
  src/main/java/capstone/recipable/domain/auth/dto/response/EmailCodeResponse.java
  src/main/java/capstone/recipable/domain/auth/oauth/controller/KakaoController.java
  src/main/java/capstone/recipable/domain/auth/service/EmailService.java
  src/main/java/capstone/recipable/domain/auth/service/LoginService.java
  src/main/java/capstone/recipable/domain/auth/service/RegisterService.java
  src/main/java/capstone/recipable/domain/user/controller/UserController.java
  src/main/java/capstone/recipable/domain/user/dto/request/UpdateUserInfo.java
  src/main/java/capstone/recipable/domain/user/dto/response/UserInfoResponse.java
  src/main/java/capstone/recipable/domain/user/entity/User.java
  src/main/java/capstone/recipable/domain/user/service/UserService.java
  src/main/java/capstone/recipable/domain/youtube/service/YoutubeService.java
Labels: feature

#32 [feat] : naver clova ocr 텍스트 분석 및 카테고리 분류 기능 구현
  build.gradle
  src/main/java/capstone/recipable/domain/ingredient/controller/IngredientController.java
  src/main/java/capstone/recipable/domain/ingredient/controller/dto/response/IngredientListResponse.java
  src/main/java/capstone/recipable/domain/ingredient/controller/dto/response/IngredientResponse.java
  src/main/java/capstone/recipable/domain/ingredient/service/NaverOcrService.java
  src/main/java/capstone/recipable/domain/ingredient/service/PredictService.java
Labels: feature

#34 [refactor] : 영수증 분석 api swagger 설명 추가
  src/main/java/capstone/recipable/domain/ingredient/controller/IngredientController.java
Labels: refactor

#36 [feat] : 냉장고 관련 api 구현
  src/main/java/capstone/recipable/domain/category/repository/CategoryRepository.java
  src/main/java/capstone/recipable/domain/expiration/entity/Expiration.java
  src/main/java/capstone/recipable/domain/expiration/repository/ExpirationRepository.java
  src/main/java/capstone/recipable/domain/ingredient/controller/dto/request/UpdateIngredientRequest.java
  src/main/java/capstone/recipable/domain/ingredient/controller/dto/response/IngredientDetailResponse.java
  src/main/java/capstone/recipable/domain/ingredient/entity/Ingredient.java
  src/main/java/capstone/recipable/domain/ingredient/repository/IngredientRepository.java
  src/main/java/capstone/recipable/domain/refrigerator/controller/RefrigeratorController.java
  src/main/java/capstone/recipable/domain/refrigerator/dto/response/RefrigeratorDetailResponse.java
  src/main/java/capstone/recipable/domain/refrigerator/dto/response/RefrigeratorListResponse.java
  src/main/java/capstone/recipable/domain/refrigerator/dto/response/RefrigeratorResponse.java
  src/main/java/capstone/recipable/domain/refrigerator/repository/RefrigeratorRepository.java
  src/main/java/capstone/recipable/domain/refrigerator/service/RefrigeratorService.java
  src/main/java/capstone/recipable/global/error/ErrorCode.java
Labels: feature

#37 Fix: 레시피 상세 생성, 조회
  src/main/java/capstone/recipable/domain/expiration/entity/Expiration.java
  src/main/java/capstone/recipable/domain/ingredient/entity/Ingredient.java
  src/main/java/capstone/recipable/domain/recipe/controller/RecipeController.java
  src/main/java/capstone/recipable/domain/recipe/dto/request/CreateRecipeRequest.java
  src/main/java/capstone/recipable/domain/recipe/dto/response/RecipeDetailsResponse.java
  src/main/java/capstone/recipable/domain/recipe/dto/response/RecipeVideoResponse.java
  src/main/java/capstone/recipable/domain/recipe/entity/Recipe.java
  src/main/java/capstone/recipable/domain/recipe/entity/RecipeVideos.java
  src/main/java/capstone/recipable/domain/recipe/repository/RecipeVideosRepository.java
  src/main/java/capstone/recipable/domain/recipe/service/RecipeService.java
  src/main/java/capstone/recipable/domain/recipe/service/YoutubeService.java
  src/main/java/capstone/recipable/domain/refrigerator/entity/Refrigerator.java
  src/main/java/capstone/recipable/domain/refrigerator/service/RefrigeratorService.java
  src/main/java/capstone/recipable/domain/user/controller/UserController.java
  src/main/java/capstone/recipable/domain/youtube/controller/YoutubeController.java
  src/main/java/capstone/recipable/global/HealthCheckApi.java
  src/main/java/capstone/recipable/global/error/ErrorCode.java
Labels: fix

#39 [feat] : naver image 검색 로직 및 냉장고 재료 추가 api 구현
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/capstone/recipable/domain/category/entity/Category.java
  src/main/java/capstone/recipable/domain/category/repository/CategoryRepository.java
  src/main/java/capstone/recipable/domain/expiration/repository/ExpirationRepository.java
  src/main/java/capstone/recipable/domain/ingredient/controller/IngredientController.java
  src/main/java/capstone/recipable/domain/ingredient/entity/Ingredient.java
  src/main/java/capstone/recipable/domain/ingredient/service/NaverSearchImageService.java
  src/main/java/capstone/recipable/domain/refrigerator/controller/RefrigeratorController.java
  src/main/java/capstone/recipable/domain/refrigerator/dto/CreateIngredientListRequest.java
  src/main/java/capstone/recipable/domain/refrigerator/repository/RefrigeratorRepository.java
  src/main/java/capstone/recipable/domain/refrigerator/service/CreateIngredientService.java
  src/main/java/capstone/recipable/domain/refrigerator/service/RefrigeratorService.java
  src/main/java/capstone/recipable/global/error/ErrorCode.java
Labels: feature, refactor

#41 [feat] : s3 setting 및 식재료 이미지 관련 로직 추가
  build.gradle
  src/main/java/capstone/recipable/domain/ingredient/controller/dto/request/UpdateIngredientRequest.java
  src/main/java/capstone/recipable/domain/ingredient/controller/dto/response/IngredientDetailResponse.java
  src/main/java/capstone/recipable/domain/ingredient/repository/IngredientRepository.java
  src/main/java/capstone/recipable/domain/refrigerator/controller/RefrigeratorController.java
  src/main/java/capstone/recipable/domain/refrigerator/service/CreateIngredientService.java
  src/main/java/capstone/recipable/domain/refrigerator/service/RefrigeratorService.java
  src/main/java/capstone/recipable/global/entity/Uuid.java
  src/main/java/capstone/recipable/global/error/ErrorCode.java
  src/main/java/capstone/recipable/global/s3/AmazonConfig.java
  src/main/java/capstone/recipable/global/s3/AmazonS3Manager.java
  src/main/java/capstone/recipable/global/s3/UuidRepository.java
Labels: feature, chore, refactor

#43 Feat: 북마크 api 구현
  src/main/java/capstone/recipable/domain/bookmark/controller/BookmarkController.java
  src/main/java/capstone/recipable/domain/bookmark/entity/Bookmark.java
  src/main/java/capstone/recipable/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/capstone/recipable/domain/bookmark/service/BookmarkService.java
  src/main/java/capstone/recipable/domain/recipe/dto/response/RecipeSummaryResponse.java
  src/main/java/capstone/recipable/domain/recipe/entity/Recipe.java
  src/main/java/capstone/recipable/domain/recipe/service/RecipeService.java
  src/main/java/capstone/recipable/domain/refrigerator/controller/RefrigeratorController.java
  src/main/java/capstone/recipable/domain/refrigerator/dto/request/CreateIngredientListRequest.java
  src/main/java/capstone/recipable/domain/refrigerator/service/CreateIngredientService.java
  src/main/java/capstone/recipable/global/error/ErrorCode.java
Labels: feature
